### ISSUE TITLE
Matrix testing with version from go.mod file

### ISSUE THREAD

**Issue by Jacalz** [WillAbides/setup-go-faster#34]
Similar to https://github.com/actions/setup-go/issues/450, it would be nice to be able to specify `go.mod` (or any other path to a Go module) as an input to the `go-version` parameter. The benefit of this over `go-version-file` is that you can have a workflow with matrix testing using the version from `go.mod` as the lowest version and any newer versions. Basically, this makes it possible to write GitHub actions that are more or less maintenance free (the below example testing the lowest supported Go version and the latest stable):

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'go.mod', 'stable' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
```
